/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup GameAssets;
extern const Sifteo::AssetImage OperatorBackground;
extern const Sifteo::AssetImage GameOver;
extern const Sifteo::AssetImage TimerBackground;
extern const Sifteo::PinnedAssetImage Font;
extern const Sifteo::PinnedAssetImage Font2;
extern const Sifteo::PinnedAssetImage FontRed;
extern const Sifteo::PinnedAssetImage FontGreen;
extern const Sifteo::AssetImage ConnectCube;
extern const Sifteo::AssetImage QuestionerBackground;
extern const Sifteo::AssetImage Timebar;
extern const Sifteo::AssetImage pixelsWhite;
extern const Sifteo::AssetImage BlackImage;
extern const Sifteo::AssetImage StripeTile;
extern const Sifteo::AssetImage TimebarAnim[9];
extern const Sifteo::AssetImage Highlights[2];
extern const Sifteo::AssetImage OperImages[5];
extern const Sifteo::AssetImage OperImagesRed[4];
extern const Sifteo::AssetImage Countdown[3];
extern const Sifteo::AssetImage OperImagesGreen[4];
