/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup BetterflowAssets;
extern const Sifteo::PinnedAssetImage BgTile;
extern const Sifteo::PinnedAssetImage StripeTile;
extern const Sifteo::AssetImage IconPrac;
extern const Sifteo::AssetImage IconRules;
extern const Sifteo::AssetImage IconComp;
extern const Sifteo::AssetImage IconMult;
extern const Sifteo::AssetImage IconCoop;
extern const Sifteo::AssetImage IconProf;
extern const Sifteo::AssetImage Tip2;
extern const Sifteo::AssetImage IconSing;
extern const Sifteo::AssetImage IconBack;
extern const Sifteo::AssetImage IconNum2;
extern const Sifteo::AssetImage IconNum3;
extern const Sifteo::AssetImage IconNum4;
extern const Sifteo::AssetImage Tip0;
extern const Sifteo::AssetImage Tip1;
extern const Sifteo::AssetImage Footer;
extern const Sifteo::AssetImage LabelEmpty;
extern const Sifteo::AssetImage LabelPrac;
extern const Sifteo::AssetImage LabelComp;
extern const Sifteo::AssetImage LabelMult;
extern const Sifteo::AssetImage LabelCoop;
extern const Sifteo::AssetImage LabelProf;
extern const Sifteo::AssetImage LabelRules;
extern const Sifteo::AssetImage LabelSing;
extern const Sifteo::AssetImage LabelBack;
