/*
 * Generated by STIR. Do not edit by hand.
 */

#include <sifteo/asset.h>

#pragma once

extern Sifteo::AssetGroup IconAssets;
extern const Sifteo::AssetImage Icon;
extern Sifteo::AssetGroup GameAssets;
extern const Sifteo::AssetImage OperatorBackground;
extern const Sifteo::AssetImage StatsBackground;
extern const Sifteo::AssetImage GameOver;
extern const Sifteo::PinnedAssetImage Font;
extern const Sifteo::PinnedAssetImage Font2;
extern const Sifteo::PinnedAssetImage FontRed;
extern const Sifteo::PinnedAssetImage FontGreen;
extern const Sifteo::AssetImage ConnectCube;
extern const Sifteo::AssetImage TimerBackground;
extern const Sifteo::AssetImage QuestionerBackground;
extern const Sifteo::AssetImage Timebar;
extern const Sifteo::AssetImage pixelsWhite;
extern const Sifteo::AssetImage BlackImage;
extern Sifteo::AssetGroup MenuImageAssets;
extern const Sifteo::PinnedAssetImage BgTile;
extern const Sifteo::PinnedAssetImage StripeTile;
extern const Sifteo::AssetImage IconPrac;
extern const Sifteo::AssetImage IconComp;
extern const Sifteo::AssetImage IconMult;
extern const Sifteo::AssetImage IconCoop;
extern const Sifteo::AssetImage IconStats;
extern const Sifteo::AssetImage IconRules;
extern const Sifteo::AssetImage IconSing;
extern const Sifteo::AssetImage IconBack;
extern const Sifteo::AssetImage IconNorm;
extern const Sifteo::AssetImage IconNum2;
extern const Sifteo::AssetImage IconNum3;
extern const Sifteo::AssetImage IconNum4;
extern const Sifteo::AssetImage Tip0;
extern const Sifteo::AssetImage Tip1;
extern const Sifteo::AssetImage Tip2;
extern const Sifteo::AssetImage Footer;
extern const Sifteo::AssetImage LabelEmpty;
extern const Sifteo::AssetImage LabelPrac;
extern const Sifteo::AssetImage LabelComp;
extern const Sifteo::AssetImage LabelMult;
extern const Sifteo::AssetImage LabelCoop;
extern const Sifteo::AssetImage LabelStats;
extern const Sifteo::AssetImage LabelRules;
extern const Sifteo::AssetImage LabelSing;
extern const Sifteo::AssetImage LabelBack;
extern const Sifteo::AssetImage LabelNorm;
extern const Sifteo::AssetImage LabelNumPlayers;
extern const Sifteo::AssetImage TimebarAnim[9];
extern const Sifteo::AssetImage OperImagesGreen[4];
extern const Sifteo::AssetImage RulesBackground[4];
extern const Sifteo::AssetImage Highlights[2];
extern const Sifteo::AssetImage OperImages[5];
extern const Sifteo::AssetImage OperImagesRed[4];
extern const Sifteo::AssetImage Countdown[3];
