APP = Operators

include $(SDK_DIR)/Makefile.defs

OBJS = $(ASSETS).gen.o ./main.o ./Cubes/Result.o ./Cubes/Timer.o ./Cubes/Question.o ./Cubes/Operator.o ./Cubes/Questioner.o ./Cubes/QuestionList.o ./Modes/Normal.o ./Modes/Mode.o ./Modes/PlayGame.o ./Modes/Practise.o
ASSETDEPS += ../assets/*.png $(ASSETS).lua

ASSETS_BUILD_PROOF := yes

include $(SDK_DIR)/Makefile.rules
